# Generated by Django 3.1.3 on 2021-03-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20210323_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='bid',
        ),
    ]
