# Generated by Django 3.1.3 on 2021-03-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_remove_watchlist_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctioneer',
            name='user',
        ),
    ]
