# Generated by Django 3.1.3 on 2021-03-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auto_20210323_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
