# Generated by Django 3.1.3 on 2021-03-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_listing_sold_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sold_out',
            field=models.BooleanField(),
        ),
    ]
