# Generated by Django 3.1.3 on 2021-05-14 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='custormer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='store.customer'),
        ),
    ]
