# Generated by Django 3.1.3 on 2021-05-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210514_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
